<svelte:head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chronik – Thierberger Schützen</title>
    <meta name="description" content="Die Geschichte der Thierberger Schützen – eine Tradition, die seit Generationen in Kufstein weitergeführt wird.">
    <meta name="keywords" content="Thierberger Schützen, Chronik, Geschichte, Tradition, Kufstein, Schützenverein, Historie">
    <meta name="author" content="Thierberger Schützen">
    <meta property="og:title" content="Chronik – Thierberger Schützen">
    <meta property="og:description" content="Erfahren Sie mehr über die traditionsreiche Geschichte der Thierberger Schützen von den Anfängen bis heute.">
    <meta property="og:url" content="https://www.thierberger-schuetzen.at/about/chronik">
    <meta property="og:type" content="website">
</svelte:head>
<div class="bg-gray-100 px-8 py-2 rounded-xl">
    <h3 class="text-2xl md:text-3xl font-extrabold dark:text-white my-3">Chronik</h3>
    <p class="my-3">Die Geschichte der Thierberger Schützen ist tief mit der Entwicklung der Region verwurzelt und reicht bis ins Jahr 1848 zurück, als die Schützenkompanie Thierberg offiziell gegründet wurde. In einer Zeit politischer Umbrüche und nationaler Bewegungen entstanden vielerorts Bürgerwehren, um die Sicherheit der Gemeinden zu gewährleisten. Auch in der Hofmark Thierberg schlossen sich Männer zusammen, um ihre Heimat zu schützen und die Tradition des Schützenwesens zu pflegen.</p>
    <p class="my-3">Im Laufe des 19. Jahrhunderts entwickelte sich die Schützenkompanie weiter und wurde zu einer festen Größe im gesellschaftlichen Leben. Besondere Bedeutung hatte die Verbindung zu Kufstein, wo die Thierberger Schützen vor dem Ersten Weltkrieg den ersten Zug der Kufsteiner Kompanie stellten. Während des Krieges wurde das Schützenwesen stark zurückgedrängt, und mit dem Ende des Konflikts sowie der Auflösung der Standschützen 1918 kam die Tradition in Thierberg vorerst zum Stillstand.</p>
    <p class="my-3">Ein Neuanfang erfolgte 1922, als unter der Federführung des Gastwirts Alfons Nocker die Thierberger Schützengilde gegründet wurde. Sie setzte die alte Schützentradition fort, nun mit einem stärkeren Fokus auf den sportlichen Aspekt des Schießens. In den ersten Jahren diente die Gilde nicht nur der Pflege des Schießsports, sondern auch als Treffpunkt für die Gemeinschaft, mit regelmäßigen Wettkämpfen und geselligen Veranstaltungen.</p>
    <p class="my-3">Wie viele Vereine erlitt auch die Schützengilde während des Zweiten Weltkriegs einen schweren Einschnitt, das Vereinsleben kam weitgehend zum Erliegen. Doch bereits wenige Jahre nach Kriegsende begann der Wiederaufbau, und ein bedeutendes Zeichen des Neuanfangs war die Weihe der neuen Schützenfahne am 14. Mai 1951, die bis heute ein zentrales Symbol der Gemeinschaft darstellt. In den darauffolgenden Jahrzehnten wurde das sportliche Schießen weiterentwickelt, und mit dem Bau des Schießstands in Morsbach erhielten die Schützen eine dauerhafte Heimstätte für Training und Wettkämpfe.</p>
    <p class="my-3">Ein weiterer bedeutender Moment war die offizielle Wiedergründung der Schützenkompanie Thierberg im Jahr 1975, womit die militärische Tradition des Schützenwesens wieder in das Vereinsleben integriert wurde. Seither ist die Kompanie regelmäßig bei kirchlichen Festen, Gedenkveranstaltungen und Prozessionen präsent und vertritt die Thierberger Schützen in historischen Uniformen bei offiziellen Anlässen.    </p>
    <p class="my-3">Eng verbunden mit der Geschichte der Schützen ist der Thierbergturm, eine Burganlage aus dem 13. Jahrhundert, die als Wahrzeichen der Region gilt. Über die Jahre hinweg haben sich die Thierberger Schützen immer wieder für den Erhalt und die Pflege dieser historischen Stätte eingesetzt und tragen dazu bei, das kulturelle Erbe der Region lebendig zu halten.</p>
    <p class="my-3">Heute sind die Thierberger Schützen eine Gemeinschaft, die Tradition und Moderne vereint. Neben dem Schießsport und der Brauchtumspflege engagieren sie sich aktiv im gesellschaftlichen Leben der Region. Als Veranstalter des Maibaumfests sorgen sie für die Bewahrung alter Bräuche und als Standbetreiber beim Zeller Fest für gesellige Begegnungen. Mit ihrer langen Geschichte und dem Blick in die Zukunft stehen sie für Zusammenhalt, Ehre und Kameradschaft, Werte, die von Generation zu Generation weitergegeben werden.</p>
</div>